export const ActionTypes = {
  GET_ALL_LOOMPAS: "GET_ALL_LOOMPAS",
  GET_ONE_LOOMPA: "GET_ONE_LOOMPA",
  SET_OOMPAS_LIST_NO_DUPLICATE: "SET_OOMPAS_LIST_NO_DUPLICATE",
  SET_DATE_GET_ONE_OOMPA: "SET_DATE_GET_ONE_OOMPA",
  OOMPAS_ERROR: "OOMPAS_ERROR",
  RESET_ALL_OOMPAS: "RESET_ALL_OOMPAS",
};